export const search = () => ({})
export const searchByArtist = () => ({})
export const searchByAlbums = () => ({})
export const searchByTracks = () => ({})
export const searchByPlaylists = () => ({})
